version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - tf_version=$TERRAFORM_VERSION
      - tf_state_key="gaming/demo/cannon-mosquito-server"
      - tf_state_bucket=$(aws s3 ls --output text | awk '{print $3}' | grep tfstate-)
      - tf_state_bucket_region="ap-southeast-1"
      - AWS_DEFAULT_REGION="ap-southeast-1"
      - wget https://releases.hashicorp.com/terraform/"$TERRAFORM_VERSION"/terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - unzip terraform_"$TERRAFORM_VERSION"_linux_amd64.zip
      - mv terraform /usr/local/bin/
  build:
    commands:
      - terraform --version
      - terraform init -backend-config="bucket=${tf_state_bucket}" -backend-config="key=${tf_state_key}" -backend-config="region=${tf_state_bucket_region}"
      - terraform validate
      - terraform plan -lock=false -input=false
      - terraform apply --auto-approve
